# Generated by Django 2.2.7 on 2020-01-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='num',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ser',
            field=models.PositiveIntegerField(default=0, verbose_name='Серия'),
        ),
    ]
