# Generated by Django 2.2.7 on 2020-01-15 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200115_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='voted',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
