# Generated by Django 2.2.7 on 2020-01-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя кандидата')),
                ('image', models.ImageField(upload_to='photos', verbose_name='Фотография')),
                ('move', models.CharField(max_length=255, verbose_name='Выдвеженец')),
                ('votes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Кандидат',
                'verbose_name_plural': 'Кандидаты',
                'ordering': ['name'],
            },
        ),
    ]
