# Generated by Django 2.2.9 on 2020-01-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя кандидата')),
                ('image', models.CharField(max_length=255, verbose_name='Фотография')),
                ('move', models.CharField(max_length=255, verbose_name='Выдвеженец')),
                ('votes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Кандидат',
                'verbose_name_plural': 'Кандидаты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя избирателя')),
                ('ser', models.PositiveIntegerField(default=0, verbose_name='Серия')),
                ('num', models.PositiveIntegerField(default=0, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата выдачи')),
                ('given', models.TextField(verbose_name='Кем выдан')),
                ('code', models.PositiveIntegerField(default=0, verbose_name='Код подразделения')),
                ('adress', models.CharField(max_length=255, verbose_name='Адрес прописки')),
            ],
            options={
                'verbose_name': 'Голосующий',
                'verbose_name_plural': 'Голосующие',
                'ordering': ['name'],
            },
        ),
    ]
