# Generated by Django 3.0.2 on 2020-01-20 18:12

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='voter',
        ),
        migrations.AddField(
            model_name='candidat',
            name='voter',
            field=models.ManyToManyField(blank=True, related_name='candidats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='theme',
            name='date_ended',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 25, 18, 12, 44, 309814, tzinfo=utc)),
        ),
    ]
