# Generated by Django 2.2.7 on 2020-01-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='move',
            field=models.CharField(max_length=255, verbose_name='Иписание'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Кандидата'),
        ),
    ]
