# Generated by Django 3.0.2 on 2020-01-18 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='users_voted',
            field=models.ManyToManyField(blank=True, related_name='themes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidat',
            name='theme',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.Theme'),
        ),
    ]
