# Generated by Django 2.2.9 on 2020-01-05 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Candidate',
            new_name='Candidat',
        ),
    ]
