# Generated by Django 2.2.7 on 2020-01-15 18:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_auto_20200115_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='move',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Кандидат'),
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название темы')),
                ('description', models.TextField(blank=True)),
                ('date_ended', models.DateTimeField(default=datetime.datetime(2020, 1, 20, 18, 49, 5, 970866, tzinfo=utc))),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('users_voted', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['date_ended'],
            },
        ),
        migrations.AddField(
            model_name='candidat',
            name='theme',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.Theme'),
        ),
    ]
