# Generated by Django 2.2.9 on 2020-01-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200106_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='voted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voter',
            name='date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
    ]
