# Generated by Django 2.2.7 on 2020-01-15 18:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200115_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='date_ended',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 20, 18, 50, 5, 298547, tzinfo=utc)),
        ),
    ]
