# Generated by Django 3.0.2 on 2020-01-21 18:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0003_auto_20200121_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='date_voted',
        ),
        migrations.AlterField(
            model_name='candidat',
            name='theme',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Theme'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='date_ended',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 26, 18, 33, 4, 620303, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='DateVoted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_voted', models.DateTimeField(auto_now_add=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Candidat')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
