# Generated by Django 2.2.9 on 2020-01-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200106_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='given',
            field=models.TextField(verbose_name='Кем выдан паспорт'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Ф.И.О.'),
        ),
    ]
