# Generated by Django 2.2.9 on 2020-01-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200106_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='date',
            field=models.DateField(verbose_name='Дата рождения (в формате дд.мм.гггг)'),
        ),
    ]
