# Generated by Django 2.2.7 on 2020-01-15 19:28

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200115_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='date_ended',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 20, 19, 28, 11, 908102, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='theme',
            name='users_voted',
            field=models.ManyToManyField(blank=True, related_name='themes', to=settings.AUTH_USER_MODEL),
        ),
    ]
