# Generated by Django 3.0.2 on 2020-01-22 15:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0004_auto_20200121_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datevoted',
            options={'ordering': ['candidat'], 'verbose_name': 'Дата голоса', 'verbose_name_plural': 'Даты голоса'},
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='voter',
        ),
        migrations.AlterField(
            model_name='datevoted',
            name='candidat',
            field=models.CharField(max_length=255, verbose_name='За кого'),
        ),
        migrations.AlterField(
            model_name='datevoted',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='date_ended',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 27, 15, 24, 51, 752484, tzinfo=utc)),
        ),
        migrations.AlterModelTable(
            name='datevoted',
            table='date_voted',
        ),
    ]
