# Generated by Django 2.2.9 on 2020-01-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200106_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service', verbose_name='Служебная картинка')),
            ],
            options={
                'verbose_name': 'Служебная картинка',
                'verbose_name_plural': 'Служебные картинки',
                'ordering': ['image'],
            },
        ),
        migrations.AlterField(
            model_name='candidat',
            name='image',
            field=models.ImageField(upload_to='photos', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voted',
            field=models.BooleanField(default=False, verbose_name='Голос'),
        ),
    ]
