# Generated by Django 2.2.9 on 2020-01-11 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200111_0951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
