# Generated by Django 2.2.7 on 2020-01-17 21:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200115_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='date_ended',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 22, 21, 41, 17, 381660, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='theme',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
