# Generated by Django 2.2.7 on 2020-01-17 21:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200118_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='date_ended',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 22, 21, 52, 55, 593757, tzinfo=utc)),
        ),
    ]
